CREATE TABLE IF NOT EXISTS gallery (
  id SERIAL PRIMARY KEY,
  nama TEXT NOT NULL,
  kategori TEXT NOT NULL DEFAULT 'Hias',
  deskripsi TEXT DEFAULT '',
  img TEXT NOT NULL DEFAULT '',
  files JSONB DEFAULT '[]',
  ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT
);

CREATE INDEX IF NOT EXISTS idx_gallery_ts ON gallery(ts DESC);
